CREATE TYPE public."account_type" AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public."account_type"
    OWNER TO cse340nv_user;

--Table structure for table 'classification'--
CREATE TABLE public.classification (
classification_id INT GENERATED BY DEFAULT AS IDENTITY,
classification_name CHARACTER VARYING NOT NULL, 
CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

--Table structure for table 'inventory'
CREATE TABLE IF NOT EXISTS public.inventory
(
 inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 inv_make character varying NOT NULL, 
 inv_model character varying NOT NULL,
 inv_year character(4) NOT NULL,
 inv_description text NOT NULL, 
 inv_image character varying NOT NULL,
 inv_thumbnail character varying NOT NULL,
 inv_price numeric(9,0) NOT NULL,
 inv_miles integer NOT NULL, 
 inv_color character varying NOT NULL,
 clasification_id integer NOT NULL,
 CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
 
);

--Table structure for table 'account'
CREATE TABLE IF NOT EXISTS public.account
(
 account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
 account_firstname character varying NOT NULL, 
 account_lastname character varying NOT NULL,
 account_email character varying NOT NULL,
 account_password character varying NOT NULL, 
 account_type account_type NOT NULL DEFAULT 'Client' :: account_type,
 CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

INSERT INTO public.account (first_name, last_name, email, notes)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

UPDATE public.account
SET account_type = 'admin'
WHERE first_name = 'Tony' AND last_name = 'Stark';


-- Update GM Hammer interior to 'huge interior'
UPDATE inventory
SET interior = 'huge interior'
WHERE make = 'GM' AND model = 'Hammer';

DELETE FROM public.account
WHERE first_name = 'Tony' AND last_name = 'Stark';

SELECT i.make, i.model, c.classification_name
FROM inventory i
INNER JOIN classification c
ON i.classification_id = c.classification_id
WHERE c.classification_name = 'Sport';


UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');